name: subtitle_player
description: A library for synchronizing subtitles for video and audio playback.
version: 1.0.0
repository: https://github.com/crazelu/subtitle_player
issue_tracker: https://github.com/Crazelu/subtitle_player/issues
topics: [subtitle, webvtt, lrc, subrip, srt, audio, video]

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0
