name: subtitle_player
description: A Flutter package for synchronizing subtitles for video and audio playback.
version: 0.0.1
repository: https://github.com/crazelu/subtitle_player

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.24.0
